/* JavaScript란? html이 뼈대, css가 피부라면, JavaScript는 뇌라고 할 수 있다.
굉장히 자유도가 높은 언어기 떄문에 여러 분야에서 쓰인다. ex) web, 모바일 앱, 서버, 머신 러닝 등등..
JavaScript특징: 
1. 프로토타입의 객체 지향 언어 이다. 하지만, 상속과 class의 개념이 없다. 
2. script 언어로 컴파일 과정을 거치지 않고 실시간으로 텍스트를 분석하여 실행한다.
3. JS의 함수는 일급 객체이다.
4. 동적 형변환이다. 값에 따라 변수의 형변환이 이루어진다.

장점:
1. script 언어라서 컴파일 과정 없이 빠르게 실행할 수 있다.
2. script 엔진이 있는 모든 운영체제에서 사용이 가능하다.
3. 일급 객체언어이기 떄문에 개발자의 역량에 따라 함수를 통하여 무한한 가능성의언어를 개발 할 수있다.

단점
1. 컴파일되지 않은 언어가 사용자에게 그대로 주어지므로 소스 노출의 위험이 크다.
2. 브라우저 상에서 소스를 변경하여 사용자가 임의의 기능을 실행할 수 있다는 위험이 있다.

JS로 할 수 있는 것들
1. 웹 개발
HTML과 CSS의 정적인 부분을 좀 더 풍부하게 만들어주는 보조역할을 넘어 핵심 역할을 담당하게 되었다. spa라이브러리와 프레임워크들이 나타나면서 웹 개발을 하는 사람들에게는 필수 언어가 되었다.

2. 서버 개발
node.js를 통해 서버 개발이 가능하다.(node.js는 크롬v8엔진으로 빌드된 JS 런타임이다. 런타임이란, 프로그래밍언어가 구동되는 환경을 말한다.)
서버 설치 부터 화면 띄우는 것 까지 금방 처리 할 수 있어서 많은 서버 개발자들이 node.js를 이용하여 JS를 사용하게 되면서 node.js는 서버 개발이라는 인식이 생겼다.

3. 앱 어플리케이션 개발
약간 생소한데 가능은 하다.

4. 머신러닝
tensorflow란 구글에서 만든 딥러닝 프로그램이다. 대게 파이썬으로 개발이 되지만 JS도 지원해서 사용은 가능하다.

//1. 자바스크립트 기본 문법
//변수와 상수(let, const)
let a = 10; //let은 내용을물 바꿀 수 있는 변수 선언 방법
console.log(a);
const b = 20; //내용물을 바꿀 수 없는 선언 방법

//자료형
let age = 18; //숫자, 따옴표 없이 그냥 씀, 수학적 계산 가능
//infinity 무한대 ex) 10/0
//NaN(not a number) 수학 계산이 불가능할떄 나오는 값

let school = '군서고'; //문자, 따옴표 감싸 표현한다
//문자를 작성하는 방법이 'a', "a", `a`가 있다. 이중 백틱(``) 방식이 가독성이 좋아서 실무에서 가장 많이 쓰인다
console.log(school.repeat(5));
let f = false; // 참과 거짓 두개만 존재

//undefined: 정의되지 않음(상자에 아무것도 없음)
let und;
console.log(und);

//null: 비어있음(상자에 아무것도 넣지 않겠다는 메모만 존재)
let n = null;
console.log(n);

//연산자 
//사칙연산 +, -, *,/ (문자열 더하기는 가능 예를들어 '안녕'+'하세요')
//비교 연산자 ===(양쪽이 완전히 같은가), !==(양쪽이 다른가), <, >, <=, >=

let name = '오현건';
let age2 = 18;
let job = '학생';
console.log('제 이름은 ' + name + '이고 나이는 ' + age2 + '살이고 직업은 ' + job + '입니다.')

//1. 조건문

let v = `안녕하세요`;
if (v === `안녕하세요`){
    console.log(1000);
}
else if (v === `안녕히가세요`){
    console.log(100000);
}
else{
    console.log(10)
}


//값이 완벽하게 똑같나를 찾는 switch문

switch (v){
    case '안녕히가세요':
        console.log(100000);
        break;
    case '안녕하세요':
        console.log(10);
        break;
    default:
        console.log(10);
}

//2. 반복문

for (let i = 0; i < 10; i+=2){
    console.log(i);
    
}

while (age <= 100){
    console.log('살아잇는');
    age++;
}

//3. 함수

ff = 10
function fun(ff){
    console.log(ff*5);
}
fun(1);

function fruit(apple){
    let juice = apple + ' juice';
    return(juice);
}

const add = (a, b)=>{
    return a+b;
}



const calculator = (a, b, c)=>{
    switch(b){
        case '+':
            return a+c;
            break;
        case '-':
            return a-c;
            break;
        case '*':
            return a*c;
            break;
        case '/':
            return a/c;
            break;
        default:
            return '이상한거 씀'
    }
}

console.log(calculator(10,'+',1000))
